# application.yml

webmail:
  api:
    version: api/v1

sendgrid:
  baseuri: https://api.sendgrid.com
  endpoint: /v3/mail/send
  apikey: ${SENDGRID_API_KEY}

mailgun:
  baseuri: https://api.mailgun.net
  endpoint: /v3/sandboxd941fefd63804f0c8df97e143ba40406.mailgun.org/messages
  apikey: ${MAILGUN_API_KEY}
