# application.yml

webmail:
  api:
    version: api/v1

sendgrid:
  baseuri: https://api.sendgrid.com
  endpoint: /v3/mail/send
  apikey: ${SENDGRID_API_KEY}

mailgun:
  baseuri: https://test.mailgun.host
  endpoint: /v3/mail/send