# application.yml

webmail:
  api:
    version: api/v1

## SENDGRID_API_KEY Should be set in environment variable (eg. export SENDGRID_API_KEY='<YOUR_KEY>')
sendgrid:
  baseuri: https://api.sendgrid.com
  endpoint: /v3/mail/send
  apikey: ${SENDGRID_API_KEY}

## MAILGUN_API_KEY Should be set in environment variable (eg. export MAILGUN_API_KEY='key:<YOUR_KEY>')
mailgun:
  baseuri: https://api.mailgun.net
  endpoint: /v3/sandboxd941fefd63804f0c8df97e143ba40406.mailgun.org/messages
  apikey: ${MAILGUN_API_KEY}

spring:
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    ROOT: INFO
    com.siteminder.webmail: DEBUG
